### PR TITLE
Support SHA256 fingerprint section

### PR DESCRIPTION
**Pull request by porkbeans**
Hello!

KRL specification seems to be updated.
SHA256 Fingerprint section added.
https://github.com/openssh/openssh-portable/commit/9405c6214f667be604a820c6823b27d0ea77937d#diff-dc34a52e14d01098362c1974a9ace0b2

### CODE REVIEW

**Comment by porkbeans** [comment]
Sorry, the page after I signed in CLA assistant doesn't show anything.
Somebody please help me!
cla-assistant io

**Comment by porkbeans** [comment]
Thank you. I signed.

**Review by hans-stripe — APPROVED** [review]
Thanks for making this PR, and sorry for the long wait! I took a look and the code and additional test looks great. I'm going to go ahead and merge this PR now!

**Comment by porkbeans** [comment]
@hans-stripe 
Thank you so much!
I'm honored to have contributed to this project!

**Pull request merged**
